<!DOCTYPE html>
<html>
<head>
    <title>ExplAgora - gérer les controverses</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script type="text/javascript" src="http://rawgit.com/vitmalina/w2ui/master/dist/w2ui.min.js"></script>
    <link rel="stylesheet" type="text/css" href="http://rawgit.com/vitmalina/w2ui/master/dist/w2ui.min.css" />
</head>
<body>

<div id="main" style="width: 100%; height: 800px;"></div>

<script type="text/javascript">
var uti = <?php echo $this->uti;?>;
var rsListes, rsLivres, rsProblemes, dataFormProbleme;
var itemListe, itemLivre, itemProb, itemReponse;

//modification des propriétés globales
//w2utils.locale('fr-fr');
var btn = w2obj.grid.prototype.buttons;
btn['add'].caption     = 'Ajouter';

var optGridShow = {header:true,		
	toolbar:true,
	toolbarReload:true,
	toolbarColumns:true,
	toolbarSearch:true,
	toolbarAdd:false,
	toolbarDelete:uti.role=="lecteur" ? false : false,
	selectColumn	:false,
	footer: true};



// widget configuration
var config = {
    layoutMain: {
        name: 'layoutMain',
        padding: 4,
        panels: [
            { type: 'top', size: '60px', resizable: false, content: '<h1 align="center">Gérer les controverses</h1>'},
            { type: 'left', size: '50%', resizable: true, minSize: 300 },
            { type: 'main', minSize: 300 }
        ]
    },
    layoutContro: {
        name: 'layoutContro',
        padding: 4,
        panels: [
            { type: 'top', size: '50%', resizable: true  },
            { type: 'main', size: '50%', resizable: true}
        ]
    },
    layoutBU: {
        name: 'layoutBU',
        padding: 4,
        panels: [
            { type: 'left', size: '60%', resizable: true},
            { type: 'main', size: '40%', resizable: true}
        ]
    },
    gridProbleme: { 
        name: 'gridProbleme',
		header: 'Les problèmes disponibles',
        show: optGridShow,
        /*
		{"recid":"1","doc_id_liste":"186","titreListe":"Jeux en biblioth\u00e8que"
		,"doc_id_livre":"188","titreLivre":"Serious game"
		,"uti_id_auteur":"1","login":"explagora"
		,"idQuestion":"2","valeur":"Une bonne question"
		,"idsC":"3,1,2","valids":"1,1,0","idsInd":"6,4,5","valInd":"lkjlkj lkjlkj ,12,jjhjkh jkh "
		,"nbReponse":"0"
		,"idC0":"3","idInd0":"6","valInd0":"lkjlkj lkjlkj ","validInd0":"1"
		,"idC1":"1","idInd1":"4","valInd1":"12","validInd1":"1"
		,"idC2":"2","idInd2":"5","valInd2":"jjhjkh jkh ","validInd2":"0"}       
        */
        columns: [
            { field: 'recid', caption: 'recid', hidden: true },
            { field: 'uti_id_auteur', caption: 'idAuteur', hidden: true },
            { field: 'login', caption: "Nom de l'auteur", size: '33%', sortable: true},
            { field: 'doc_id_liste', caption: 'idListe', hidden: true },
            { field: 'titreListe', caption: 'Titre de la liste', size: '33%', sortable: true},
            { field: 'titreLivre', caption: 'Titre du livre', size: '33%', sortable: true},
            { field: 'valeur', caption: 'Votre question', size: '60%', sortable: true },
            { field: 'nbReponse', caption: 'Nb de réponse', size: '33%', sortable: true},
            { field: 'valInd0', caption: 'Indice 1', size: '33%', sortable: true },
            { field: 'valInd1', caption: 'Indice 2', size: '33%' },
            { field: 'valInd2', caption: 'Indice 3', size: '33%' },
            { field: 'valInd3', caption: 'Indice 4', size: '33%' }
            
        ],
        toolbar: {
            items: [
                { id: 'ajoutProb', type: 'button', caption: 'Ajouter un problème', icon: ' fa-external-link'},
            ],
            onClick: function (event) {
                if (event.target == 'ajoutProb') {
		            var idListe = w2ui.gridListe.getSelection();
		            if(!idListe.length){
			             w2alert('Veuillez sélectionner une liste.').ok(function () { console.log('ok'); });
			             return;
		            }           
		            var idLivre = w2ui.gridLivre.getSelection();
		            if(!idLivre.length){
			             w2alert('Veuillez sélectionner un livre.').ok(function () { console.log('ok'); });
			             return;
		            }
		            itemListe = w2ui.gridListe.get(idListe[0]);
		            itemLivre = w2ui.gridListe.get(idLivre[0]);
		            showFormProbleme();
                }
            }
        },          
        records: [
        ],
		onAdd: function(event) {            
	    },
	    onClick: function(event) {
            var grid = this;
            var form = w2ui.form;
            console.log(event);
            event.onComplete = function () {
                var sel = gridProbleme.getSelection();
                console.log(sel);
            }
        }
    },
    gridReponse: { 
        name: 'gridReponse',
		header: 'Les réponses au problème',
        show: optGridShow,
        /*
		{"recid":"1","doc_id_liste":"186","titreListe":"Jeux en biblioth\u00e8que"
		,"doc_id_livre":"188","titreLivre":"Serious game"
		,"uti_id_auteur":"1","login":"explagora"
		,"idQuestion":"2","valeur":"Une bonne question"
		,"idsC":"3,1,2","valids":"1,1,0","idsInd":"6,4,5","valInd":"lkjlkj lkjlkj ,12,jjhjkh jkh "
		,"nbReponse":"0"
		,"idC0":"3","idInd0":"6","valInd0":"lkjlkj lkjlkj ","validInd0":"1"
		,"idC1":"1","idInd1":"4","valInd1":"12","validInd1":"1"
		,"idC2":"2","idInd2":"5","valInd2":"jjhjkh jkh ","validInd2":"0"}       
        */
        columns: [
            { field: 'recid', caption: 'recid', hidden: true },
            { field: 'uti_id_jouer', caption: 'idJoueur', hidden: true },
            { field: 'login', caption: "Nom du joueur", size: '33%', sortable: true},
            { field: 'valeur', caption: 'Réponse', size: '33%', sortable: true },
            { field: 'created', caption: 'Date', size: '33%' }            
        ],
        toolbar: {
            items: [
                { id: 'ajoutRep', type: 'button', caption: 'Ajouter une réponse', icon: ' fa-external-link'},
            ],
            onClick: function (event) {
                if (event.target == 'ajoutRep') {
		            var idProb = w2ui.gridProbleme.getSelection();
		            if(!idProb.length){
			             w2alert('Veuillez sélectionner un problème.').ok(function () { console.log('ok'); });
			             return;
		            }           
		            var itemProb = w2ui.gridProbleme.get(idProb[0]);
		            showFormRep(itemProb);
                }
            }
        },          
        records: [
        ],
		onAdd: function(event) {            
	    },
	    onClick: function(event) {
            var grid = this;
            var form = w2ui.form;
            console.log(event);
            event.onComplete = function () {
                var sel = gridProbleme.getSelection();
                console.log(sel);
            }
        }
    },    
    formReponse: { 
        header: 'Veuillez remplir les champs obligatoires.',
        name: 'formReponse',
        fields: [
	    		//{ name: 'idListe', type: 'text', html: { caption: 'idListe', attr: 'size="50" readonly' } },
        		{ name: 'titreListe', type: 'text', required : true, html: { caption: 'Nom de la liste', attr: 'size="50" readonly' } },
            //{ name: 'idLivre', type: 'text', html: { caption: 'idLivre', attr: 'size="10" readonly' } },
            { name: 'titreLivre', type: 'text', required : true, html: { caption: 'Titre du livre', attr: 'style="width:90%" readonly' } },
            //{ name: 'idAuteur', type: 'text', html: { caption: 'idAuteur', attr: 'size="50" readonly' } },
            { name: 'nomAuteur', type: 'text', required : true, html: { caption: 'Auteur de la question', attr: 'size="50" readonly' } },
            { name: 'question', type: 'textarea', required : true, html: { caption: 'Texte de la question', attr: 'style="margin-left:0px;width: 90%; height: 100px; resize: none"' } },
			{ name: 'indice1', type: 'text', required : true, html: { caption: 'Premier indice', attr: 'size="50" maxlength="40"' } },
			{ name: 'valid1', type: 'checkbox', html: {caption: 'valide'} },
			{ name: 'indice2', type: 'text', required : true, html: { caption: 'Deuxième indice', attr: 'size="50" maxlength="40"' } },
			{ name: 'valid2', type: 'checkbox', html: {caption: 'valide'} },
			{ name: 'indice3', type: 'text', html: { caption: 'Troisième indice', attr: 'size="50" maxlength="40"' } },
			{ name: 'valid3', type: 'checkbox', html: {caption: 'valide'} },
			{ name: 'indice4', type: 'text', html: { caption: 'Quatrième indice', attr: 'size="50" maxlength="40"' } },
			{ name: 'valid4', type: 'checkbox', html: {caption: 'valide'} },
        ],
        actions: {
            Annuler: function () {
                this.clear();
            },
            Valider: function () {
                var errors = this.validate();
                if (errors.length > 0) return;
				//enregistre les données dans la base
				ajouteProbleme(w2ui['formProbleme'].record);
            }
        }
    },
    formProbleme: { 
        header: 'Veuillez remplir les champs obligatoires.',
        name: 'formProbleme',
        fields: [
	    		//{ name: 'idListe', type: 'text', html: { caption: 'idListe', attr: 'size="50" readonly' } },
        		{ name: 'titreListe', type: 'text', required : true, html: { caption: 'Nom de la liste', attr: 'size="50" readonly' } },
            //{ name: 'idLivre', type: 'text', html: { caption: 'idLivre', attr: 'size="10" readonly' } },
            { name: 'titreLivre', type: 'text', required : true, html: { caption: 'Titre du livre', attr: 'style="width:90%" readonly' } },
            //{ name: 'idAuteur', type: 'text', html: { caption: 'idAuteur', attr: 'size="50" readonly' } },
            { name: 'nomAuteur', type: 'text', required : true, html: { caption: 'Auteur de la question', attr: 'size="50" readonly' } },
            { name: 'question', type: 'textarea', required : true, html: { caption: 'Texte de la question', attr: 'style="margin-left:0px;width: 90%; height: 100px; resize: none"' } },
			{ name: 'indice1', type: 'text', required : true, html: { caption: 'Premier indice', attr: 'size="50" maxlength="40"' } },
			{ name: 'valid1', type: 'checkbox', html: {caption: 'valide'} },
			{ name: 'indice2', type: 'text', required : true, html: { caption: 'Deuxième indice', attr: 'size="50" maxlength="40"' } },
			{ name: 'valid2', type: 'checkbox', html: {caption: 'valide'} },
			{ name: 'indice3', type: 'text', html: { caption: 'Troisième indice', attr: 'size="50" maxlength="40"' } },
			{ name: 'valid3', type: 'checkbox', html: {caption: 'valide'} },
			{ name: 'indice4', type: 'text', html: { caption: 'Quatrième indice', attr: 'size="50" maxlength="40"' } },
			{ name: 'valid4', type: 'checkbox', html: {caption: 'valide'} },
        ],
        actions: {
            Annuler: function () {
                this.clear();
            },
            Valider: function () {
                var errors = this.validate();
                if (errors.length > 0) return;
				//enregistre les données dans la base
				ajouteProbleme(w2ui['formProbleme'].record);
            }
        }
    },    
    gridListe: { 
        name     : 'gridListe',
		header: 'Les listes de la BU présentes dans ExplAgora',		
        show: optGridShow,
        columns: [      
            { field: 'recid', hidden:true, caption: 'ID', size: '50px', sortable: true, resizable: true },
            { field: 'text', caption: 'Titre de la liste', size: '40%', sortable: true, resizable: true},		            
            { field: 'url', hidden:true, caption: 'Lien vers le site de la BU', size: '60%', sortable: true, resizable: true, editable: { type: 'text'}},
        ],
        toolbar: {
            items: [
                { id: 'voirLien', type: 'button', caption: 'Voir le détail', icon: ' fa-external-link'},
                { id: 'ajoutListe', type: 'button', caption: 'Ajouter une liste', icon: ' fa-external-link'},
            ],
            onClick: function (event) {
                if (event.target == 'voirLien') {
		            var id = w2ui.gridListe.getSelection();
		            if(!id) w2alert('Veuillez sélectionner une liste.').ok(function () { console.log('ok'); });

		            var item = w2ui.gridListe.get(id);
                		open(item[0].url,"_blank")
                }
                if (event.target == 'ajoutListe') {
                    //affiche la popup
                    w2prompt({
                        label       : 'N° de la liste',
                        value       : '',
                        attrs       : 'style="width: 200px"',
                        title       : w2utils.lang('Ajouter une liste dans ExplAgora'),
                        ok_text     : w2utils.lang('Ok'),
                        cancel_text : w2utils.lang('Annuler'),
                        width       : 400,
                        height      : 200
                    })
                    .change(function (event) {
                        console.log('change', event);
                    })
                    .ok(function (event) {
                        console.log('ok', event);
                        ajouteListe(event);
                    });
                }
            }
        },        
        records: rsListes,        
        onRender: function(event) {
        		w2ui.gridListe.lock('Chargement...', true);	
        		event.onComplete = function () {
        			w2ui.gridListe.unlock();
        	    }		        
        },
        onDelete: function(event) {
	    },
        onAdd: function(event) {            
            
	    },
        onClick: function (event) {
            var itemSelect = this.get(event.recid);
            chargeLivre(itemSelect.tronc);          			           		           
        }	
    },    
    formListe: { 
        name     : 'formListe',
        fields: [
            { field: 'Listes disponibles',html: { attr: 'style="width: 100%;"' }, type: 'list', required: true, 
                options: { items: rsListes } },
            { field: 'N° de la liste à ajouter', type: 'text', required: false },
        ],
        actions: {
        },
        onChange: function (event) {
            console.log(event);
            chargeLivre(event.value_new.tronc)
        }
    },
    gridLivre: { 
        name: 'gridLivre',
		header: 'Livre de la liste',		
        show: optGridShow,
        columns: [
            { field: 'recid', hidden:true, caption: 'id BU P8', size: '33%', sortable: true },
            { field: 'idDoc', hidden:true, caption: 'id ExplAgore', size: '33%', sortable: true },
            { field: 'titre', caption: 'Titre du livre', size: '30%', sortable: true  },
            { field: 'url', hidden:true, caption: 'Lien vers la fiche BU', size: '70%', sortable: true, editable: { type: 'text'} }
        ],
	 	toolbar: {
            items: [
                { id: 'voirLien', type: 'button', caption: 'Voir le détail', icon: ' fa-external-link'},
            ],
            onClick: function (event) {
                if (event.target == 'voirLien') {
		            var id = w2ui.gridLivre.getSelection();
		            var item = w2ui.gridLivre.get(id);
                		open(item[0].url,"_blank")
                }
            }
        },
        records: [],
        onClick: function(event) {
            var grid = this;
            var form = w2ui.form;
            console.log(event);
            event.onComplete = function () {
                //récupère les données du livre
                var sel = grid.getSelection();
                var livre = grid.get(sel)[0];
                //récupère les données de la liste
                var liste = w2ui.gridListe.get(w2ui.gridListe.getSelection())[0];
                console.log(sel);
                //construction des donnée
                dataFormProbleme = {
                		idListe:liste.recid,
                		titreListe:liste.titre,
                		idLivre:livre.recid,
                		titreLivre:livre.titre,
                		idAuteur:uti.idUti,
                		nomAuteur:uti.nom
                };                
            }
        }
    }           
};
$(function () {
	$.getJSON( "../bup8?obj=getListe", function( data ) {
					
		rsListes = data;
	    
	    //récupère les questions
		$.getJSON( "../controverse/probleme", function( data1 ) {
			rsProblemes = data1;
			
			//initialisation des objet w2ui
		    $('#main').w2layout(config.layoutMain);
		    w2ui.layoutMain.content('left', $().w2layout(config.layoutBU));
		    w2ui.layoutMain.content('main', $().w2layout(config.layoutContro));

		    w2ui.layoutContro.content('top', $().w2grid(config.gridProbleme));

			w2ui.layoutBU.content('left', $().w2grid(config.gridListe));
			w2ui.layoutBU.content('main', $().w2grid(config.gridLivre));

		    $().w2form(config.formProbleme);

			//chargement des données
		    	w2ui['gridProbleme'].clear();
		    	w2ui['gridProbleme'].add(rsProblemes);			        	

		    	w2ui['gridListe'].clear();
		    	w2ui['gridListe'].add(rsListes);			        	
		    	
		});
	    		
	});
	    
});
function chargeLivre(tronc){
    var url = "../bup8?obj=getListeLivre&idListe="+tronc;
	$.getJSON(url, function( data ) {
	    	console.log(data);
	    rsLivres = data;
		//format la liste
	    
	    	w2ui['gridLivre'].clear();
	    	w2ui['gridLivre'].add( rsLivres.livres);			        	
	});                            
	
}
function ajouteListe(id){
    var url = "../bup8?obj=setListe&idListe="+id;
	$.getJSON(url, function( data ) {
	    	chargeListes();		        	
	    rsLivres = data;
		//format la liste	    
	    	w2ui['gridLivre'].clear();
	    	w2ui['gridLivre'].add( rsLivres.livres);	
	});                            
	
}
function chargeListes(){
	$.getJSON( "../bup8?obj=getListe", function( data ) {		
		rsListes = data;
	    	w2ui['gridListe'].clear();
	    	w2ui['gridListe'].add( rsListes);			        	
		
	});
	
}

function ajouteProbleme(data){
    var url = "../controverse/creer";
    var dt = {"table":"probleme","data":data};
	$.getJSON(url, dt, function( rep ) {
		console.log(rep);
        w2alert('Le problème est ajouté.').ok(function () { console.log('ok'); });		
        w2ui.gridProbleme.add(rep);
        w2ui.gridProbleme.selectNone();
	});                            
	
}
function showFormProbleme(){
	$().w2popup('open', {
        title   : "Ajout d'un problème",
        body    : '<div id="form" style="width: 100%; height: 100%;"></div>',
        style   : 'padding: 15px 0px 0px 0px',
        width   : 600,
        height  : 800, 
        showMax : true,
        onToggle: function (event) {
            $(w2ui.formProbleme.box).hide();
            event.onComplete = function () {
                $(w2ui.formProbleme.box).show();
                w2ui.formProbleme.resize();
            }
        },
        onOpen: function (event) {
            event.onComplete = function () {
                // specifying an onOpen handler instead is equivalent to specifying an onBeforeOpen handler, which would make this code execute too early and hence not deliver.
                w2ui.formProbleme.record = dataFormProbleme;
                w2ui.formProbleme.refresh();                
                $('#w2ui-popup #form').w2render('formProbleme');
            }
        }
    });	
}

showFormRep(itemProb){
	$().w2popup('open', {
        title   : "Ajout d'une réponse",
        body    : '<div id="form" style="width: 100%; height: 100%;"></div>',
        style   : 'padding: 15px 0px 0px 0px',
        width   : 600,
        height  : 800, 
        showMax : true,
        onToggle: function (event) {
            $(w2ui.formReponse.box).hide();
            event.onComplete = function () {
                $(w2ui.formReponse.box).show();
                w2ui.formReponse.resize();
            }
        },
        onOpen: function (event) {
            event.onComplete = function () {
                // specifying an onOpen handler instead is equivalent to specifying an onBeforeOpen handler, which would make this code execute too early and hence not deliver.
                w2ui.formReponse.record = dataFormReponse;
                w2ui.formReponse.refresh();                
                $('#w2ui-popup #form').w2render('formReponse');
            }
        }
    });	
}


</script>

</body>
</html>
