<!DOCTYPE html>
<html>
<head>
    <title>ExplAgora - gérer les controverses</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script type="text/javascript" src="http://rawgit.com/vitmalina/w2ui/master/dist/w2ui.min.js"></script>
    <link rel="stylesheet" type="text/css" href="http://rawgit.com/vitmalina/w2ui/master/dist/w2ui.min.css" />
</head>
<body>

<div id="main" style="width: 100%; height: 800px;"></div>

<script type="text/javascript">
var idAuteur = <?php echo $this->idAuteur;?>;

var listes, livres;


// widget configuration
var config = {
    layoutMain: {
        name: 'layoutMain',
        padding: 4,
        panels: [
            { type: 'top', size: '300px', resizable: false},
            { type: 'left', size: '50%', resizable: true, minSize: 300 },
            { type: 'main', minSize: 300 }
        ]
    },
    layoutTop: {
        name: 'layoutTop',
        padding: 4,
        panels: [
            { type: 'top', size: '100px', resizable: false, content: '<h1>Gérer les controverses</h1>'  },
            { type: 'left', size: '50%', resizable: true, minSize: 300},
            { type: 'main', size: '50%', minSize: 300   }
        ]
    },
    grid: { 
        name: 'grid',
        show: {
            toolbar          : true,
            toolbarDelete    : true
        },
        columns: [
            { field: 'question', caption: 'Votre question', size: '33%', sortable: true, searchable: true },
            { field: 'indice1', caption: 'Indice 1', size: '33%', sortable: true, searchable: true },
            { field: 'indice2', caption: 'Indice 2', size: '33%' },
            { field: 'indice3', caption: 'Indice 3', size: '33%', render: 'date' },
            { field: 'indice4', caption: 'Indice 4', size: '33%', render: 'date' }
        ],
        records: [
            { recid: 1, fname: 'John', lname: 'Doe', email: 'jdoe@gmail.com', sdate: '4/3/2012' },
            { recid: 2, fname: 'Stuart', lname: 'Motzart', email: 'jdoe@gmail.com', sdate: '4/3/2012' },
            { recid: 3, fname: 'Jin', lname: 'Franson', email: 'jdoe@gmail.com', sdate: '4/3/2012' },
            { recid: 4, fname: 'Susan', lname: 'Ottie', email: 'jdoe@gmail.com', sdate: '4/3/2012' },
            { recid: 5, fname: 'Kelly', lname: 'Silver', email: 'jdoe@gmail.com', sdate: '4/3/2012' },
            { recid: 6, fname: 'Francis', lname: 'Gatos', email: 'jdoe@gmail.com', sdate: '4/3/2012' },
            { recid: 7, fname: 'Mark', lname: 'Welldo', email: 'jdoe@gmail.com', sdate: '4/3/2012' },
            { recid: 8, fname: 'Thomas', lname: 'Bahh', email: 'jdoe@gmail.com', sdate: '4/3/2012' },
            { recid: 9, fname: 'Sergei', lname: 'Rachmaninov', email: 'jdoe@gmail.com', sdate: '4/3/2012' }
        ],
        onClick: function(event) {
            var grid = this;
            var form = w2ui.form;
            console.log(event);
            event.onComplete = function () {
                var sel = grid.getSelection();
                console.log(sel);
                if (sel.length == 1) {
                    form.recid  = sel[0];
                    form.record = $.extend(true, {}, grid.get(sel[0]));
                    form.refresh();
                } else {
                    form.clear();
                }
            }
        }
    },
    form: { 
        header: 'Edit Record',
        name: 'form',
        fields: [
            { name: 'recid', type: 'text', html: { caption: 'ID', attr: 'size="10" readonly' } },
            { name: 'fname', type: 'text', required: true, html: { caption: 'First Name', attr: 'size="40" maxlength="40"' } },
            { name: 'lname', type: 'text', required: true, html: { caption: 'Last Name', attr: 'size="40" maxlength="40"' } },
            { name: 'email', type: 'email', html: { caption: 'Email', attr: 'size="30"' } },
            { name: 'sdate', type: 'date', html: { caption: 'Date', attr: 'size="10"' } }
        ],
        actions: {
            Reset: function () {
                this.clear();
            },
            Save: function () {
                var errors = this.validate();
                if (errors.length > 0) return;
                if (this.recid == 0) {
                    w2ui.grid.add($.extend(true, { recid: w2ui.grid.records.length + 1 }, this.record));
                    w2ui.grid.selectNone();
                    this.clear();
                } else {
                    w2ui.grid.set(this.recid, this.record);
                    w2ui.grid.selectNone();
                    this.clear();
                }
            }
        }
    },
    formListe: { 
        name     : 'formListe',
        fields: [
            { field: 'Listes disponibles',html: { attr: 'style="width: 100%;"' }, type: 'list', required: true, 
                options: { items: listes } },
            { field: 'N° de la liste à ajouter', type: 'text', required: false },
        ],
        actions: {
        },
        onChange: function (event) {
            console.log(event);
            var url = "../bup8?obj=getListeLivre&idListe="+event.value_new.tronc;
	        	$.getJSON(url, function( data ) {
		        	console.log(data);
		        	livres = data;
		        	w2ui['gridLivre'].clear();
		        	w2ui['gridLivre'].add( livres.livres);			        	
	        	});
                
            
        }
    },
    gridLivre: { 
        name: 'gridLivre',
        show: {
            toolbar          : true,
            toolbarDelete    : true
        },
        columns: [
            { field: 'recid', caption: 'id BU P8', size: '33%', sortable: true, searchable: true },
            { field: 'idDoc', caption: 'id ExplAgore', size: '33%', sortable: true, searchable: true },
            { field: 'titre', caption: 'Titre du livre', size: '33%', sortable: true, searchable: true  }
        ],
        records: [],
        onClick: function(event) {
            var grid = this;
            var form = w2ui.form;
            console.log(event);
            event.onComplete = function () {
                var sel = grid.getSelection();
                console.log(sel);
                if (sel.length == 1) {
                    form.recid  = sel[0];
                    form.record = $.extend(true, {}, grid.get(sel[0]));
                    form.refresh();
                } else {
                    form.clear();
                }
            }
        }
    }           
};

$(function () {

	$.getJSON( "../bup8?obj=getListe", function( data ) {
					
		listes = data;
		config.formListe.fields[0].options.items = listes;
	    // initialization
	    
	    $('#main').w2layout(config.layoutMain);
	    w2ui.layoutMain.content('top', $().w2layout(config.layoutTop));
	    w2ui.layoutMain.content('left', $().w2grid(config.grid));
	    w2ui.layoutMain.content('main', $().w2form(config.form));
		w2ui.layoutTop.content('left', $().w2form(config.formListe));
		w2ui.layoutTop.content('main', $().w2grid(config.gridLivre));
	});
	    
});
</script>

</body>
</html>